# Render Blueprint API
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: hvac-troubleshooting-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false

# Uncomment this section if you want to use Render's MongoDB service
# databases:
#   - name: hvac-app-db
#     plan: free
#     databaseName: hvac_app
#     user: hvac_app_user